enableTelemetry: false
enableGlobalCache: true

nodeLinker: node-modules

npmAuthToken: '${NPM_AUTH_TOKEN:-}'

npmPublishAccess: public

npmScopes:
  crowdbotics:
    npmAuthToken: '${NPM_AUTH_TOKEN:-}'
    npmPublishRegistry: 'https://npm.pkg.github.com'

preferInteractive: true

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.6.0.cjs
